# autogenerated by docgen
# source: /home/runner/work/nimskull/nimskull/lib/js/asyncjs.nim
# rdoccmd: -d:nimExperimentalAsyncjsThen
import "/home/runner/work/nimskull/nimskull/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim"
import "/home/runner/work/nimskull/nimskull/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim"
