#[
autogenerated by docgen
loc: /home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim(74, 3)
rdoccmd: 
]#
import "/home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim", 74, 3).}:
  doAssert (big"9" - big"1") == big"8"

