#[
autogenerated by docgen
loc: /home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim(38, 3)
rdoccmd: 
]#
import "/home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim", 38, 3).}:
  doAssert big"2147483647".toCstring(2) == "1111111111111111111111111111111".cstring

