#[
autogenerated by docgen
loc: /home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim(61, 3)
rdoccmd: 
]#
import "/home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim", 61, 3).}:
  doAssert (big("3") + big("2") ** big("66")).wrapToUint(66) == big("3")

