#[
autogenerated by docgen
loc: /home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim(140, 3)
rdoccmd: 
]#
import "/home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nimskull/nimskull/lib/std/jsbigints.nim", 140, 3).}:
  doAssert (big"999" shr big"2") == big"249"

