# autogenerated by docgen
# source: /home/runner/work/nimskull/nimskull/lib/js/jsconsole.nim
# rdoccmd: -r:off
import "/home/runner/work/nimskull/nimskull/doc/html/nimcache/runnableExamples/jsconsole_examples_1.nim"
