# autogenerated by docgen
# source: /home/runner/work/nimskull/nimskull/lib/js/jscore.nim
# rdoccmd: 
import "/home/runner/work/nimskull/nimskull/doc/html/nimcache/runnableExamples/jscore_examples_1.nim"
