# autogenerated by docgen
# source: /home/runner/work/nimskull/nimskull/lib/std/jsfetch.nim
# rdoccmd: -r:off
import "/home/runner/work/nimskull/nimskull/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim"
