# autogenerated by docgen
# source: /home/runner/work/nimskull/nimskull/lib/std/jsformdata.nim
# rdoccmd: -r:off
import "/home/runner/work/nimskull/nimskull/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim"
