# autogenerated by docgen
# source: /home/runner/work/nimskull/nimskull/lib/std/jsheaders.nim
# rdoccmd: -r:off
import "/home/runner/work/nimskull/nimskull/doc/html/nimcache/runnableExamples/jsheaders_examples_1.nim"
